### ISSUE TITLE
About Blog Theme

### ISSUE THREAD

**Issue by xcc3641** [alexrintt/alexrintt.github.io#4]
Hi Alex,

I remember being particularly impressed with the style of your blog earlier in the year. It had a black background, lots of little squares like stars moving up from the bottom, and your background music was particularly nice. I can't seem to find the code about them in your repository today, where else can I get it for reference and learning?

Thank you very much for your help!

**Comment by alexrintt** [comment]
Hey Hugo, thanks man!

This animation was under the legacy branch which stores the code that is no longer in use.

But I created a repository where you can see the website code: [github.com/alexrintt/rising](https://github.com/alexrintt/rising) + a p5.js sketch [p5js.org/alexrintt/rising](https://editor.p5js.org/alexrintt/full/JMamwM8a_) where you can edit the animation and see the effects (it's HTML5 canvas based).

The website is up again at [alexrintt.io/rising](https://alexrintt.io/rising)!

If you are searching for the music, I used many throughout the time, but all of them are available (or at least many of them) here: https://github.com/alexrintt/rising/tree/master/src/assets/music.

Let me know if it helps ;)

**Comment by xcc3641** [comment]
OMG! Thank you thank you thank you! I really love this style so much! Your aesthetic is really great and it's already helped me, thanks for the reply!
